product-name: p-metrics-forwarder
network-properties:
  singleton_availability_zone:
    name: ((AZ_1))
  other_availability_zones:
  - name: ((AZ_1))
  - name: ((AZ_2))
  - name: ((AZ_3))
  network:
    name: pas
resource-config:
  metrics-forwarder:
    instances: 1
