product-name: p-event-alerts
network-properties:
  singleton_availability_zone:
    name: ((AZ_1))
  other_availability_zones:
  - name: ((AZ_1))
  - name: ((AZ_2))
  - name: ((AZ_3))
  network:
    name: pas
product-properties:
  .deploy-pcf-event-alerts.instance_count:
    value: 1
  .properties.mysql.internal.plan_name:
    value: db-small
  .properties.smtp_selector:
    value: Disabled
